/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package less_mang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author kasun
 */
public class NotPaidCusId extends javax.swing.JFrame {

    /**
     * Creates new form NotPaidCusId
     */
    public NotPaidCusId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        notpaidtxt = new javax.swing.JTextField();
        notpaidbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Enter the Relavant Invoice Number");

        notpaidtxt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        notpaidbtn.setBackground(new java.awt.Color(0, 0, 0));
        notpaidbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notpaidbtn.setForeground(new java.awt.Color(0, 255, 51));
        notpaidbtn.setText("Send Invoice");
        notpaidbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notpaidbtnMousePressed(evt);
            }
        });
        notpaidbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notpaidbtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("✔️");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(notpaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(notpaidbtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(notpaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(notpaidbtn)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void notpaidbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notpaidbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notpaidbtnActionPerformed

    private void notpaidbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notpaidbtnMousePressed
        // TODO add your handling code here:
        String sinvoiceid=notpaidtxt.getText();
        int inId=Integer.parseInt(sinvoiceid);
        
        
        Connection dbconn=DBConnection.connectDB();
        if(dbconn!=null){
           
            try{
                PreparedStatement st=(PreparedStatement)
                        dbconn.prepareStatement("SELECT invoice.month,invoice.customer_ID,invoice.payment,customer_lessons.duration,customer.fname,customer.sname\n" +
"from invoice\n" +
"JOIN customer_lessons on invoice.customer_ID=customer_lessons.customer_ID\n" +
"JOIN customer on invoice.customer_ID=customer.ID\n" +
"where invoice.status='Not_Paid' AND invoice.ID=?  ;");
                
                st.setString(1, sinvoiceid);
                ResultSet res=st.executeQuery();
                if(res.next()){
                // data will be add until finish
                //String InvoiceID=String.valueOf(res.getInt("ID"));
                String Firstname=res.getString("fname");
                String Surname=res.getString("sname");
                String Duration=String.valueOf(res.getInt("duration"));
                int dur=Integer.parseInt(Duration);
                float payrate=1000;
                float paygen=payrate*(dur/60);
             
                String CustomerID=String.valueOf(res.getInt("customer_ID"));
                invoiceGEN(CustomerID,sinvoiceid,paygen);
                String Month=res.getString("month");
                //String Payment=String.valueOf(res.getFloat("payment"));
                //System.out.println(CustomerID);
                //System.out.println(paygen); 
                
   
            }
           
               //String sqlStat="UPDATE invoice set payment='"+paygenstat+"' WHERE ID='"+sinvoiceid+"'";
 
        }
            catch (SQLException ex) {
                Logger.getLogger(NotPaidCusId.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_notpaidbtnMousePressed

    }
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotPaidCusId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton notpaidbtn;
    private javax.swing.JTextField notpaidtxt;
    // End of variables declaration//GEN-END:variables

    public void invoiceGEN(String CustomerID,String invoiceID,float paygen){
        
        Connection dbconn=DBConnection.connectDB();
        String sqlStat="UPDATE invoice set payment='"+paygen+"' WHERE ID='"+invoiceID+"'";
        
         try{
             PreparedStatement pstmt=dbconn.prepareStatement(sqlStat);
             pstmt.executeUpdate();
             dispose();
             new InvoiceForm(CustomerID,invoiceID).setVisible(true);
             //System.out.println("DONE");
             
             
         }
         catch(SQLException ex){
             System.out.println(ex.getMessage());
         }
                  
        
}
   
}
     
