/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package less_mang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author kasun
 */
public class NotPaidCusId extends javax.swing.JFrame {

    /**
     * Creates new form NotPaidCusId
     */
    public NotPaidCusId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        notpaidtxt = new javax.swing.JTextField();
        notpaidbtn = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Please Enter the Customer ID ••••••••");

        notpaidtxt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        notpaidbtn.setBackground(new java.awt.Color(0, 0, 0));
        notpaidbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notpaidbtn.setForeground(new java.awt.Color(0, 255, 51));
        notpaidbtn.setText("Send Invoice");
        notpaidbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notpaidbtnMousePressed(evt);
            }
        });
        notpaidbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notpaidbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(notpaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(notpaidbtn)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(notpaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(notpaidbtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void notpaidbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notpaidbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notpaidbtnActionPerformed

    private void notpaidbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notpaidbtnMousePressed
        // TODO add your handling code here:
        String sinvoiceid=notpaidtxt.getText();
        int inId=Integer.parseInt(sinvoiceid);
        Connection dbconn=DBConnection.connectDB();
        if(dbconn!=null){
            try{
                PreparedStatement st=(PreparedStatement)
                        dbconn.prepareStatement("SELECT invoice.month,invoice.ID,invoice.customer_ID,invoice.payment,customer_lessons.duration,customer.fname,customer.sname \n" +
"from invoice \n" +
"JOIN customer_lessons on invoice.customer_ID=customer_lessons.customer_ID\n" +
"JOIN customer on invoice.customer_ID=customer.ID\n" +
"where invoice.status='Not_Paid';");
                
                ResultSet res=st.executeQuery();
                while(res.next()){
                // data will be add until finish
                String InvoiceID=String.valueOf(res.getInt("ID"));
                String Firstname=res.getString("fname");
                String Surname=res.getString("sname");
                String Duration=String.valueOf(res.getInt("duration"));
                String CustomerID=String.valueOf(res.getInt("customer_ID"));
                String Month=res.getString("month");
                String Payment=String.valueOf(res.getFloat("payment"));
            } 
            
        }
            catch (SQLException ex) {
                Logger.getLogger(NotPaidCusId.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_notpaidbtnMousePressed
  }
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotPaidCusId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotPaidCusId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton notpaidbtn;
    private javax.swing.JTextField notpaidtxt;
    // End of variables declaration//GEN-END:variables
}
        
